---
deployment:
      tasks:
        - export DEPLOYPATH=/home/gljo4uxrniy6/public_html/rootaccess.ksusalinawebdev.net
        - /bin/cp style.css $DEPLOYPATH 
        - /bin/cp/templates * $DEPLOYPATH 